import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Medium Lite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="w-screen h-screen flex flex-col overflow-hidden">
            <div className="w-full h-full flex flex-col overflow-y-auto">
              <Navbar />
              <div className="w-full h-full relative flex flex-col justify-start">
                {children}
              </div>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
