import HomeMain from "@/components/home/home-main";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Medium Lite - Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <HomeMain />
    </>
  );
}
